ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN /bin/bash -c 'set -eux; \
  apt-get update \
  --allow-releaseinfo-change \
  --allow-releaseinfo-change-suite \
  --allow-releaseinfo-change-origin \
  --allow-releaseinfo-change-label; \
  apt-get install -y --no-install-recommends \
    tree \
    iproute2 \
    net-tools \
    tcpdump \
    ros-humble-urdf-tutorial \
    ros-humble-ros-gz \
    ros-humble-teleop-twist-keyboard \
  ; \
  rm -rf /var/lib/apt/lists/*'
